CREATE TABLE stadium
(
    id              bigint auto_increment primary key,
    admin_id        bigint       not null,
    name            varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
    x_size          int          not null,
    y_size          int          not null,
    size            varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
    is_used         boolean      not null,
    price           int          not null,
    door_type       varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
    stadium_type    varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
    cover_image     bigint       null,
    address         varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
    detail_address   varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null,
    opening_time    time         not null,
    closing_time    time         not null,
    is_parking      boolean      not null,
    is_parking_free boolean      not null,
    parking_info    varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci null,
    is_shower       boolean      not null,
    is_shower_free  boolean      not null,
    shower_info     varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci null,
    is_wear         boolean      not null,
    is_wear_free    boolean      not null,
    wear_info       varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci null,
    is_shoes        boolean      not null,
    is_shoes_free   boolean      not null,
    shoes_info      varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci null,
    is_ball         boolean      not null,
    ball_info       varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci null,
    is_toilet       boolean      not null,
    intro           varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci null,
    promise         varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci null,
    created_at      datetime     null,
    created_by      bigint       null,
    updated_at      datetime     null,
    updated_by      bigint       null
);